a, b = 6, 3
print(f"a = {a}, b = {b}")
print(f"Addition: {a+b}")
print(f"Subtraction: {a-b}")
print(f"Multiplication: {a*b}")
print(f"Division: {a/b}")
print(f"Modulus: {a%b}")
print(f"Exponentiation: {a**b}")
print(f"Floor Division: {a//b}")
print(f"Bitwise AND: {a&b}")
print(f"Bitwise OR: {a|b}")
print(f"Bitwise XOR: {a^b}")
print(f"Left Shift: {a<<1}, Right Shift: {a>>1}")
print(f"Negation: {-a}, Bitwise NOT: {~a}")
print("End of arithmetic operations")
print("Thank you for using the arithmetic operations program.")
print("Have a great day!")
print("End of the program.")
print("Goodbye!")
